# Schema for the configuration files of the soundcloudfield module.
soundcloudfield.settings:
  type: mapping
  label: 'SoundCloud'
  mapping:
    url:
      type: varchar
      label: 'URL'

field.soundcloud.settings:
  type: mapping
  label: 'SoundCloud field settings'

field.soundcloud.instance_settings:
  type: mapping
  label: 'SoundCloud field settings'

field.storage_settings.soundcloud:
  type: mapping
  label: 'SoundCloud'
  mapping:
    url:
      type: varchar
      label: 'URL'

field.widget.settings.soundcloud_url:
  type: mapping
  label: 'SoundCloud URL'
  mapping:
    placeholder_url:
      type: string
      label: 'Placeholder for URL'
    url:
      type: string
      label: 'SoundCloud URL'

field.formatter.settings.soundcloud_default:
  type: mapping
  label: 'Default (HTML5 player)'
  mapping:
    soundcloud_player_type:
      type: string
      label: 'HTML5 player type'
    soundcloud_player_width:
      type: integer
      label: 'Width'
    soundcloud_player_height:
      type: integer
      label: 'Height'
    soundcloud_player_height_sets:
      type: integer
      label: 'Height for sets'
    soundcloud_player_visual_height:
      type: integer
      label: 'Height of the visual player'
    soundcloud_player_autoplay:
      type: boolean
      label: 'Play audio automatically when loaded (autoplay).'
    soundcloud_player_color:
      type: string
      label: 'Player color.'
    soundcloud_player_hiderelated:
      type: boolean
      label: 'Hide related tracks.'
    soundcloud_player_showartwork:
      type: boolean
      label: 'Show artwork.'
    soundcloud_player_showcomments:
      type: boolean
      label: 'Show comments.'
    soundcloud_player_showplaycount:
      type: boolean
      label: 'how play count.'
